
pool:
  vmImage: 'Ubuntu 16.04'

resources:
  containers:
  - container: dolfinx
    image: 'quay.io/fenicsproject/dolfinx:latest'

container: dolfinx

steps:
- checkout: self
  clean: true
  fetchDepth: 5
  submodules: true

- script: printenv
