jobs:
- job: Ubuntu
  displayName: Ubuntu CI Test

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - template: ./ubuntu-steps.yml

- job: MacOS
  displayName: MacOS CI Test

  pool:
    vmImage: xcode9-macos10.13

  steps:
  - template: ./macos-steps.yml
