resources:
  containers:
  - container: dolfinx
    image: 'wells/dolfinx-dev-env:openmpi'

jobs:

- job: Ubuntu
  displayName: Ubuntu CI Test

  pool:
    vmImage: 'Ubuntu 16.04'

  container: dolfinx

  steps:
  - template: ./ubuntu-steps.yml

- job: MacOS
  displayName: MacOS CI Test

  pool:
    vmImage: macOS-10.14

  steps:
  - template: ./macos-steps.yml
