
steps:
- checkout: self
  clean: true
  fetchDepth: 5
  submodules: true

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: specific
    project: fenics
    pipeline: petsc-builder
    buildVersionToDownload: latest
    downloadType: single
    artifactName: petsc_tarball
  displayName: Download PETSc install for MacOS

- bash: |
    echo $SYSTEM_ARTIFACTSDIRECTORY
    cd /
    sudo tar xvf $SYSTEM_ARTIFACTSDIRECTORY/petsc_tarball/petsc-install-macos.tar.gz
  displayName: Extract PETSc install

- bash: |
    brew update
    brew install pkg-config eigen mpich boost || true
  displayName: Install Homebrew packages

- bash: |
    pip3 -q install cffi decorator flake8 matplotlib numba pygmsh pytest pytest-xdist sphinx sphinx_rtd_theme scipy --upgrade
    pip3 install git+https://bitbucket.org/fenics-project/fiat.git --upgrade
    pip3 install git+https://bitbucket.org/fenics-project/ufl.git --upgrade
    pip3 install git+https://github.com/FEniCS/ffcx --no-deps --upgrade
  displayName: Install Python3 dependencies

- bash: |
    mkdir -p cpp/build
    cd cpp/build
    ls -l /usr/local/petsc
    export PETSC_DIR=/usr/local/petsc
    export HDF5_ROOT=/usr/local/petsc
    export HDF5_DIR=/usr/local/petsc
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
  displayName: CMake

- bash: |
    make -j4
    sudo make install
  displayName: Build and install C++
  workingDirectory: cpp/build

- bash: |
    make -j3 unittests
    ctest -R unittests
    mpirun -np 3 ctest -R unittests
  displayName: C++ Unit Tests
  workingDirectory: cpp/build

- bash: |
    export PYBIND11_VERSION=2.3.0
    wget -nc --quiet https://github.com/pybind/pybind11/archive/v${PYBIND11_VERSION}.tar.gz
    tar -xf v${PYBIND11_VERSION}.tar.gz
    cd pybind11-${PYBIND11_VERSION}
    mkdir build
    cd build
    cmake -DPYBIND11_TEST=False ..
    make install
  displayName: Install pybind11
  workingDirectory: python

- bash: |
    source /usr/local/share/dolfin/dolfin.conf
    export PETSC_DIR=/usr/local/petsc
    export HDF5_ROOT=/usr/local/petsc
    export HDF5_DIR=/usr/local/petsc
    pip3 install petsc4py==3.11.0 mpi4py
    python3 setup.py build
    sudo python3 setup.py install
  displayName: Python build
  workingDirectory: python

- bash: |
    source /usr/local/share/dolfin/dolfin.conf
    export PETSC_DIR=/usr/local/petsc
    pip3 install pytest-azurepipelines
    python3 -m pytest --test-run-title="MacOS Python Unit Tests (serial)" .
  displayName: Run Python unit tests
  workingDirectory: python/test/unit

- bash: |
    source /usr/local/share/dolfin/dolfin.conf
    export PETSC_DIR=/usr/local/petsc
    mpirun -n 3 python3 -m pytest --test-run-title="MacOS Python Unit Tests (MPI)" .
  displayName: Run Python unit tests (MPI)
  workingDirectory: python/test/unit
