
steps:
- checkout: self
  clean: true
  fetchDepth: 5
  submodules: true

- bash: |
    # apt-get -qq update
    # apt-get -y install libfreetype6-dev
    pip3 -q install cffi decorator flake8 matplotlib numba pygmsh pytest pytest-xdist sphinx sphinx_rtd_theme --upgrade
    pip3 -q install pytest-azurepipelines
    pip3 install git+https://bitbucket.org/fenics-project/fiat.git git+https://bitbucket.org/fenics-project/ufl.git git+https://github.com/FEniCS/ffcx --no-deps --upgrade
  displayName: Install dependencies


- bash: |
    mkdir -p build
    cd build
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer ../cpp/
    ninja -j3 install
  displayName: Configure and build C++

- bash: |
    # source $HOME/FEniCS/share/dolfin/dolfin.conf
    cd python
    pip3 -v install .
  displayName: Build and install Python interface
  workingDirectory: python

- bash: |
    source $HOME/FEniCS/share/dolfin/dolfin.conf
    python3 -m pytest --test-run-title="Ubuntu Python Unit Tests (serial)" .
  displayName: Python unit tests
  workingDirectory: python/test/unit

- bash: |
    cat /proc/cpuinfo
    source $HOME/FEniCS/share/dolfin/dolfin.conf
    mpirun -verbose -n 3 python3 -m pytest -s -v --test-run-title="Ubuntu Python Unit Tests (MPI)" .
  displayName: Python unit tests (MPI)
  workingDirectory: python/test/unit