
steps:
- checkout: self
  clean: true
  fetchDepth: 5
  submodules: true

- bash: |
    sudo apt-get -qq update
    sudo apt-get -y install libfreetype6-dev
    sudo pip3 -q install cffi decorator flake8 matplotlib numba pygmsh pytest pytest-xdist sphinx sphinx_rtd_theme --upgrade
    sudo pip3 -q install pytest-azurepipelines
    sudo pip3 install git+https://bitbucket.org/fenics-project/fiat.git --upgrade
    sudo pip3 install git+https://bitbucket.org/fenics-project/ufl.git --upgrade
    sudo pip3 install git+https://github.com/FEniCS/ffcx --upgrade
  displayName: Install dependencies

- bash: |
    cd cpp
    mkdir build
    cd build
    cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/FEniCS ..
    ninja build
    ninja install
  displayName: Configure and build C++

- bash: |
    source $HOME/FEniCS/share/dolfin/dolfin.conf
    python3 setup.py install #--prefix=$HOME/.local
  displayName: Build and install Python interface
  workingDirectory: python

- bash: |
    source $HOME/FEniCS/share/dolfin/dolfin.conf
    python3 -m pytest --test-run-title="Ubuntu Python Unit Tests (serial)" .
  displayName: Python unit tests
  workingDirectory: python/test/unit

- bash: |
    cat /proc/cpuinfo
    source $HOME/FEniCS/share/dolfin/dolfin.conf
    mpirun -verbose -n 3 python3 -m pytest -s -v --test-run-title="Ubuntu Python Unit Tests (MPI)" .
  displayName: Python unit tests (MPI)
  workingDirectory: python/test/unit