
steps:
- checkout: self
  clean: true
  fetchDepth: 5
  submodules: true

- bash: |
    # apt-get -qq update
    # apt-get -y install libfreetype6-dev
    sudo -H pip3 -q install cffi decorator flake8 matplotlib numba pygmsh pytest pytest-xdist sphinx sphinx_rtd_theme --upgrade
    sudo -H pip3 -q install pytest-azurepipelines
    sudo -H pip3 install git+https://github.com/FEniCS/fiat.git --upgrade
    sudo -H pip3 install git+https://github.com/FEniCS/ufl.git --upgrade
    # sudo -H pip3 install git+https://github.com/FEniCS/ffcx.git --upgrade
  displayName: Install dependencies

- bash: |
    sudo -H pip3 install git+https://github.com/FEniCS/ffcx.git --upgrade
  displayName: Install dependencies (ffcx)

- bash: |
    # cd cpp && mkdir build && cd build && cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/FEniCS ..
    echo $PWD
    echo $HOME
    echo $PETSC_DIR
    cd cpp && mkdir build && cd build && cmake -G Ninja ..
    ninja
    sudo ninja install
  displayName: Configure and build C++

- bash: |
    # source $HOME/FEniCS/share/dolfin/dolfin.conf
    echo $PETSC_DIR
    echo $HOME
    echo $PWD
    # pip3 install -e .
  displayName: Build and install Python interface
  workingDirectory: python

- bash: |
    # source $HOME/FEniCS/share/dolfin/dolfin.conf
    python3 -m pytest --test-run-title="Ubuntu Python Unit Tests (serial)" .
  displayName: Python unit tests
  workingDirectory: python/test/unit

- bash: |
    cat /proc/cpuinfo
    # source $HOME/FEniCS/share/dolfin/dolfin.conf
    mpirun -verbose -n 3 python3 -m pytest -s -v --test-run-title="Ubuntu Python Unit Tests (MPI)" .
  displayName: Python unit tests (MPI)
  workingDirectory: python/test/unit